apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: block-info-hpa
  namespace: etd
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etdstats-block-info
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
