apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: etd-service
  name: worker
  namespace: etd
spec:
  ports:
    - name: "30303"
      port: 30303
      protocol: UDP
      targetPort: 30303
    - name: 30303-tcp
      port: 30303
      targetPort: 30303
  selector:
    io.kompose.service: worker
