apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project
  namespace: mongodb
data:
  baseUrl: http://143.198.86.33:8080

  # Optional Parameters
  # projectName: My Ops/Cloud Manager Project

  orgId: 618beb48b8f1c55d4d015b3b

