apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  storage-scale
  namespace: etd
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name:  storage-management-system
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50