apiVersion: v1
kind: Service
metadata:
  name: storage-management-system-service1
  namespace: etd
  labels:
    app: storage-management-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: storage-management-system
