apiVersion: v1
kind: Service
metadata:
  name: etdstats-transaction-service
  namespace: etd
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: etdstats-transaction
