apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  admin-server-scale
  namespace: etd
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name:  admin-server-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50