apiVersion: apps/v1
kind: Deployment
metadata:
  name: etdstats-analytics
  namespace: etd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etdstats-analytics
  template:
    metadata:
      labels:
        app: etdstats-analytics
    spec:
      containers:
        - name: etdstats-analytics
          image: 'ghcr.io/etherdata-blockchain/etdstats/analytics_service:1.2.0'
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"
          ports:
            - name: server-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: etdstats
                  key: DATABASE_URL
      restartPolicy: Always
