apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-management-system
  namespace: etd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-management-system
  template:
    metadata:
      labels:
        app: storage-management-system
    spec:
      containers:
        - name: storage-management-system
          image: 'sirily11/etd-storage-management-system:1.2.6'
          ports:
            - name: server-port
              containerPort: 80
              protocol: TCP

          env:
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: DB_NAME
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_S3_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: AWS_S3_REGION_NAME
            - name: AWS_DEFAULT_ENDING
              valueFrom:
                secretKeyRef:
                  name: storage-management-system
                  key: AWS_DEFAULT_ENDING
            - name: GUNICORN_CMD_ARGS
              value: "--bind=0.0.0.0:80 --workers=2"
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
