apiVersion: apps/v1
kind: Deployment
metadata:
  name: etdstats-transaction
  namespace: etd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etdstats-transaction
  template:
    metadata:
      labels:
        app: etdstats-transaction
    spec:
      containers:
        - name: etdstats-transaction
          image: 'ghcr.io/etherdata-blockchain/etdstats/transaction_service:1.9.0'
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"
          ports:
            - name: server-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: etdstats
                  key: DATABASE_URL
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  name: etdstats
                  key: RPC_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: etdstats
            - name: USER_SERVICE_URL
              value: http://etdstats-user-service.etd/stats/user

      restartPolicy: Always
