apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: etd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - storage.etdchain.net
        - stats.etdchain.net
        - stats.etd.zone
        - admin.etdchain.net
        - stats.debugchain.net
##        - service.etdchain.net
      secretName: letsencrypt-prod
  rules:
    - host: storage.etdchain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storage-management-system-service1
                port:
                  number: 80
    - host: stats.etdchain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etdstats-service
                port:
                  number: 80
    - host: stats.debugchain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etdstats-service
                port:
                  number: 80
    - host: stats.etd.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etdstats-service
                port:
                  number: 80
    - host: admin.etdchain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80
#    - host: service.etdchain.net
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: uptime-service
#                port:
#                  number: 80
