apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: metopia-co-hpa
  namespace: metopia
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metopia-co
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
