apiVersion: v1
kind: Service
metadata:
  name: etdstats-contract-service
  namespace: etdstats
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: etdstats-contract
