apiVersion: batch/v1
kind: CronJob
metadata:
  name: block-fetcher
  namespace: etd
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: block-fetcher
              image: sirily11/etd-block-fetcher:1.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: RPC_URL
                  valueFrom:
                    secretKeyRef:
                      key: RPC_URL
                      name: block-fetcher
                - name: MONGODB_URL
                  valueFrom:
                    secretKeyRef:
                      key: MONGODB_URL
                      name: block-fetcher
          restartPolicy: OnFailure

  concurrencyPolicy: Forbid
