apiVersion: batch/v1
kind: CronJob
metadata:
  name: block-fetcher
  namespace: etdstats
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: block-fetcher
              image: ghcr.io/etherdata-blockchain/cron-jobs/block_fetcher:v4.1.9
              imagePullPolicy: IfNotPresent
              env:
                - name: RPC_URL
                  valueFrom:
                    secretKeyRef:
                      key: RPC_URL
                      name: block-fetcher
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_URL
                      name: block-fetcher
                - name: DEFAULT_DB
                  value: etdstats
          restartPolicy: OnFailure

  concurrencyPolicy: Forbid
