apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-fetcher
  namespace: etd
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: block-fetcher
              image: ghcr.io/etherdata-blockchain/cron-jobs/user_fetcher:v2.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: RPC_URL
                  value: https://rpc.debugchain.net
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_URL
                      name: block-fetcher
                - name: CONTRACT_ADDRESS
                  value: 0x6802F77F219DAe947006288f406D6034baEAF085
          restartPolicy: OnFailure

  concurrencyPolicy: Forbid
